---
title: "Getting and Cleaning Data – Course Project"
author: "David Levy"
date: "11/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# call the run_analysis.R script
source('run_analysis.R')

# load libraries
library(tidyverse)
```

## Introduction


## Loading the Data




```{r Loading the data}

datafile <- 'harus.zip'
url <- 'https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip'
dir <- 'UCI HAR Dataset'

# file download if not already complete
if(!file.exists(datafile)){
        download.file(url, datafile) 
}

# unzip file if not already complete
if(!file.exists(dir)){
	unzip(datafile)
}

```

```{r Visualize some of the data}

# get activity labels from the appropriate file
activityLabels <- read_delim('UCI HAR Dataset/activity_labels.txt', ' ',
                             col_names = c('label', 'activity'))

# reformat labels to meet tidy data guidelines
activityLabels$activity <- str_to_lower(str_remove_all(activityLabels$activity, 
                                                       '[^[:alnum:]]'))

# get features from the appropriate file
features <- read_delim('UCI HAR Dataset/features.txt', ' ',
                             col_names = c('index', 'feature'))
```

```{r Visualize some of the data}

# retrieve test data
xtest <- read.table('UCI HAR Dataset/test/X_test.txt')
ytest <- read.table('UCI HAR Dataset/test/y_test.txt')
subjtest <- read.table('UCI HAR Dataset/test/subject_test.txt')

# retrieve train data
xtrain <- read.table('UCI HAR Dataset/train/X_train.txt')
ytrain <- read.table('UCI HAR Dataset/train/y_train.txt')
subjtrain <- read.table('UCI HAR Dataset/train/subject_train.txt')

# merge data
x <- rbind(xtest, xtrain)
y <- rbind(ytest, ytrain)
subj <- rbind(subjtest, subjtrain)
```

## Preparing the Data

```{r Preparing the data}

readLines('UCI HAR Dataset/test/X_test.txt', n=3)

```

## Running the Cleaning Script

```{r Running the cleaning Script}

# call the run_analysis.R script
source('run_analysis.R')

```
